Prep javascript arrays
yahnbaron/prep-0922-code-solutions pull request #11
Opened 2022-09-26 03:59 UTC by yahnbaron

![Screenshot 2022-09-25 at 8 56 55 PM](https://user-images.githubusercontent.com/113651780/192191132-a4932cc4-570b-43e5-a8ec-3a95b077c07a.png)

2022-09-26 16:56 UTC, thebearingedge requested changes

2022-09-26 16:56 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +var lastElement = languages[5];
You can get the last element of any array by subtracting 1 from the array's length

```js
var lastElement = languages[length - 1];
```

2022-09-27 05:24 UTC, yahnbaron commented
![Screenshot 2022-09-26 at 10 11 57 PM](https://user-images.githubusercontent.com/113651780/192439234-14c6ef79-1885-4278-92f4-b28f318a7757.png)

2022-09-27 16:35 UTC, thebearingedge approved these changes

2022-09-27 17:32 UTC, merged